#Denom and vars are for eff plots only
denoms:
    denom: &denom "era{global_tag}/0common_0_gen/{variable}.root:DoubleElectron_PU200"

#var, branch, xlabel (for Efficiency)
vars:
    GenEl_pt:
        snapBranch: "GenEl_pt"
        xlabel: "Gen. $p_{T}$ [GeV]"
        rebin: 3
        xlim: [-0.2, 100]
        ylim: [0., 1.1]


objs_map:
    AR2024 (Tight):
        Eff_num: "era{global_tag}/TkEleL2Tight_All_2_full/{variable}.root:DoubleElectron_PU200"
        Eff_den: *denom
        Rate: "era{global_tag}/TkEleL2Tight_All_2_full/TkEleL2_pt.root:MinBias"
        global_tag: "v131Xv3O"
    DPS (Tight):
        Eff_num: "era{global_tag}/TkEleL2Tight_All_2_full/{variable}.root:DoubleElectron_PU200"
        Eff_den: *denom
        Rate: "era{global_tag}/TkEleL2Tight_All_2_full/TkEleL2_pt.root:MinBias"
        global_tag: "v131Xv9A"
    NEW (Tight):
        global_tag: "140Xv0B18"
        #Eff
        Eff_num: "zsnap/era{global_tag}/TkEleL2Loose_All_2_full/DoubleElectron_PU200.root" #MUST BE LOOSE
        Eff_den: *denom
        genIdx: "TkEleL2_genIdx"
        #Rate
        Rate: "zsnap/era{global_tag}/TkEleL2Tight_All_2_full/MinBias.root"
        rateVar: "TkEleL2_pt"
        #Both
        score: "TkEleL2_idScore"
        binVar: "TkEleL2_pt"
        Bins: [ 0, 28, 40]
        Thrs: [ -1.00, 0.3, -1]

    AR2024 (Loose):
        Eff_num: "era{global_tag}/TkEleL2Loose_All_2_full/{variable}.root:DoubleElectron_PU200"
        Eff_den: *denom
        Rate: "era{global_tag}/TkEleL2Loose_All_2_full/TkEleL2_pt.root:MinBias"
        global_tag: "v131Xv3O"
    DPS (Loose):
        Eff_num: "era{global_tag}/TkEleL2Loose_All_2_full/{variable}.root:DoubleElectron_PU200"
        Eff_den: *denom
        Rate: "era{global_tag}/TkEleL2Loose_All_2_full/TkEleL2_pt.root:MinBias"
        global_tag: "v131Xv9A"
    NEW (Loose):
        global_tag: "140Xv0B18"
        #Eff
        Eff_num: "zsnap/era{global_tag}/TkEleL2Loose_All_2_full/DoubleElectron_PU200.root"
        Eff_den: *denom
        genIdx: "TkEleL2_genIdx"
        #Rate
        Rate: "zsnap/era{global_tag}/TkEleL2Loose_All_2_full/MinBias.root"
        rateVar: "TkEleL2_pt"
        #Both
        score: "TkEleL2_idScore"
        binVar: "TkEleL2_pt"
        Bins: [    0, 18, 28, 36]
        Thrs: [ -1.00, -0.15, 0.075, -1]


default_rate_kwargs: &default_rate_kwargs
    xlim: [0,60]
    ylim: [1, 100000]
    xlabel: "Online $p_{T}$ [GeV]"

plots:
    Tight:
        rate_kwargs: *default_rate_kwargs
        items:
            - AR2024 (Tight)
            - DPS (Tight)
            - NEW (Tight)
    Loose:
        rate_kwargs: *default_rate_kwargs
        items:
            - AR2024 (Loose)
            - DPS (Loose)
            - NEW (Loose)